
# version: 2.1
# jobs:
#   build_and_test:
#     docker:
#       - image: circleci/node:16
#     steps:
#       - checkout 
#       - run:
#           name: Install Dependencies
#           command: npm install  
#       - run:
#           name: Fix Permissions for Mocha
#           command: chmod +x node_modules/.bin/mocha
#       - run:
#           name: Fix Permissions for NYC
#           command: chmod +x ./node_modules/.bin/nyc
#       - run:
#           name: Run Tests
#           command: npm test  
#       - run:
#           name: Build app
#           command: npm run build  
#       - run:
#           name: Generate Coverage Report
#           command: npm test -- --coverage
#       - run:
#           name: Upload Coverage to Coveralls
#           command: |
#             chmod +x ./node_modules/.bin/coveralls
#             npx coveralls

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build_and_test
# version: 2.1
# jobs:
#   build_and_test:
#     docker:
#       - image: circleci/node:16
#       - image: circleci/postgres:13
#         environment:
#           POSTGRES_DB: barefoot_nomad
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     steps:
#       - checkout 
#       - run:
#           name: Install Dependencies
#           command: |
#             npm install
#             npm install coveralls --save-dev  # Add this line to install coveralls
#       - run:
#           name: Fix Permissions for Mocha
#           command: chmod +x node_modules/.bin/mocha
#       - run:
#           name: Fix Permissions for NYC
#           command: chmod +x ./node_modules/.bin/nyc
#       - run:
#           name: Run Tests
#           command: npm test  
#       - run:
#           name: Build app
#           command: npm run build  
#       - run:
#           name: Generate Coverage Report
#           command: npm test -- --coverage
#       - run:
#           name: Upload Coverage to Coveralls
#           command: |
#             npm install coveralls --save-dev  # Install coveralls if not already installed
#             cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build_and_test
version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:16
      - image: circleci/postgres:13
        environment:
          POSTGRES_DB: barefoot_nomad
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            npm install coveralls --save-dev
      - run:
          name: Wait for PostgreSQL to Be Ready
          command: |
            echo "Waiting for PostgreSQL to start..."
            for i in `seq 1 20`; do
              pg_isready -h 127.0.0.1 -p 5432 -U postgres && echo "PostgreSQL is ready!" && exit 0
              echo "Still waiting for PostgreSQL..."
              sleep 5
            done
            echo "PostgreSQL failed to start in time" && exit 1
      - run:
          name: Create Test Database
          command: |
            psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE barefoot_nomad_test;"
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build App
          command: npm run build
      - run:
          name: Generate Coverage Report
          command: npm test -- --coverage
      - run:
          name: Upload Coverage to Coveralls
          command: |
            npm install coveralls --save-dev
            cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
