# version: 2.1
# jobs:
#   build_and_test:
#     docker:
#       - image: node:16  
#     steps:
#       - checkout 
#       - run:
#           name: 'Say hello'
#           command: 'echo Hello, World!' 
#       - run:
#           name: Install Dependencies
#           command: npm install  
#       - run:
#           name: Fix Permissions for Mocha
#           command: chmod +x node_modules/.bin/mocha
#       - run:
#           name: Run Tests
#           command: npm test  
#       - run:
#           name: Build app
#           command: npm run build  

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build_and_test 
version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Start Docker Compose Services
          command: docker-compose up -d
      - run:
          name: Wait for PostgreSQL to Start
          command: |
            until docker exec postgres pg_isready -U $POSTGRES_USER; do
              echo "Waiting for PostgreSQL to start...";
              sleep 5;
            done;
            echo "PostgreSQL is ready!";
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Stop Docker Compose Services
          command: docker-compose down

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
