# version: 2.1
# jobs:
#   build_and_test:
#     docker:
#       - image: circleci/node:16
#       - image: circleci/postgres:13
#         environment:
#           POSTGRES_DB: barefoot_nomad
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     steps:
#       - checkout 
#       - run:
#           name: Install Dependencies
#           command: |
#             npm install
#             npm install coveralls --save-dev
#       - run:
#           name: Fix Permissions for Mocha
#           command: chmod +x node_modules/.bin/mocha
#       - run:
#           name: Fix Permissions for NYC
#           command: chmod +x ./node_modules/.bin/nyc
#       - run:
#           name: Run Tests
#           command: npm test  
#       - run:
#           name: Build app
#           command: npm run build  
#       - run:
#           name: Generate Coverage Report
#           command: npm test -- --coverage
#       - run:
#           name: Upload Coverage to Coveralls
#           command: |
#             npm install coveralls --save-dev
#             cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build_and_test

version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:16
      - image: circleci/postgres:13
        environment:
          POSTGRES_DB: barefoot_nomad
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    steps:
      - checkout 
      - run:
          name: Install Dependencies
          command: |
            npm install
            npm install coveralls cross-env --save-dev
      - run:
          name: Fix Permissions
          command: |
            chmod +x node_modules/.bin/mocha
            chmod +x node_modules/.bin/nyc
            chmod +x node_modules/.bin/cross-env
      - run:
          name: Modify Test File
          command: |
            sed -i '/^await db.sequelize.sync({ force: true });/d' test/userRegister.test.js
      - run:
          name: Run Tests
          command: npm test  
      - run:
          name: Build app
          command: npm run build  
      - run:
          name: Generate Coverage Report
          command: npm test -- --coverage
      - run:
          name: Upload Coverage to Coveralls
          command: |
            cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

workflows:
  version: 2
  build:
    jobs:
      - build_and_test